#proximity_node's eds => mcu.eds
[proximity]
config_file = "./mcu.eds"

#light_node's eds => DS301_profile_mcu.eds
[light]
config_file = "./DS301_profile_mcu.eds"




#bottom

[[proximity.nodes]]
node_id = 15




[[light.nodes]]
node_id = 83
