[gesture]
active_dis = 50 # in cm

[proximity]
config_file = "./eds/DS301_profile_mcu.eds"


[[proximity.nodes]]
node_id = 10
[[proximity.nodes.transform]]
x = 0
y = 0.1

[[proximity.nodes]]
node_id = 11
[[proximity.nodes.transform]]
x = 0
y = 0.4

[[proximity.nodes]]
node_id = 12
[[proximity.nodes.transform]]
x = 0
y = 0.7

[[proximity.nodes]]
node_id = 13
[[proximity.nodes.transform]]
x = 0
y = 1.0

[[proximity.nodes]]
node_id = 14
[[proximity.nodes.transform]]
x = 0
y = 1.3

[[proximity.nodes]]
node_id = 15
[[proximity.nodes.transform]]
x = 0
y = 1.6

[[proximity.nodes]]
node_id = 16
[[proximity.nodes.transform]]
x = 0.1
y = 1.7

[[proximity.nodes]]
node_id = 17
[[proximity.nodes.transform]]
x = 0.4
y = 1.7


[[proximity.nodes]]
node_id = 18
[[proximity.nodes.transform]]
x = 0.7
y = 1.7

[[proximity.nodes]]
node_id = 19
[[proximity.nodes.transform]]
x = 1.0
y = 1.7

[[proximity.nodes]]
node_id = 20
[[proximity.nodes.transform]]
x = 1.3
y = 1.7

[[proximity.nodes]]
node_id = 21
[[proximity.nodes.transform]]
x = 1.4
y = 1.7

[[proximity.nodes]]
node_id = 22
[[proximity.nodes.transform]]
x = 1.7
y = 1.7

[[proximity.nodes]]
node_id = 23
[[proximity.nodes.transform]]
x = 2.0
y = 1.7

[[proximity.nodes]]
node_id = 24
[[proximity.nodes.transform]]
x = 2.3
y = 1.7

[[proximity.nodes]]
node_id = 25
[[proximity.nodes.transform]]
x = 2.6
y = 1.7

[[proximity.nodes]]
node_id = 26
[[proximity.nodes.transform]]
x = 2.9
y = 1.7